# always run
trigger:
  branches:
    include:
      - '*'

variables:
  vmImageName: 'ubuntu-latest'

jobs:
  - job: test
    displayName: 'MPWS2019 Tests'
    pool:
      vmImage: $(vmImageName)

  steps:
    - task: Maven@3
      displayName: "Engine Tests"
      inputs:
        mavenPomFile: 'engine/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'

    - task: Maven@3
        displayName: "Benchmark Tests"
        inputs:
          mavenPomFile: 'benchmark/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'package'

