/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hpi_des_hdes_engine_indigenous_execution_operation_StreamFilter */

#ifndef _Included_de_hpi_des_hdes_engine_indigenous_execution_operation_StreamFilter
#define _Included_de_hpi_des_hdes_engine_indigenous_execution_operation_StreamFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hpi_des_hdes_engine_indigenous_execution_operation_StreamFilter
 * Method:    process
 * Signature: (Lde/hpi/des/hdes/engine/AData;)V
 */
JNIEXPORT void JNICALL Java_de_hpi_des_hdes_engine_indigenous_execution_operation_StreamFilter_process
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
